import type { CommerceStore } from "@rinads/commerce";

export const AMBADY_ORG_ID = "org_ambady_demo";
export const DEMO_CUSTOMER_ID = "cust_demo_001";

export function createAmbadySeedStore(): CommerceStore {
  const productId = "prod_pebbles_001";
  const v500 = "var_pebbles_500g";
  const v1kg = "var_pebbles_1kg";
  const v5kg = "var_pebbles_5kg";

  return {
    taxRatePercent: 5,
    products: [
      {
        id: productId,
        organizationId: AMBADY_ORG_ID,
        name: "Ambady Premium Pebbles",
        slug: "ambady-premium-pebbles",
        description:
          "Hand-selected decorative pebbles for landscaping, aquariums, and interior design. Natural finish, washed and sorted.",
        status: "published",
        categorySlug: "landscaping",
        tags: ["pebbles", "landscaping", "garden", "aquarium"],
        seoTitle: "Ambady Premium Pebbles",
        seoDescription: "Natural decorative pebbles in 500g, 1kg, and 5kg packs.",
        ratingAvg: 4.6,
        ratingCount: 128,
      },
      {
        id: "prod_river_stones",
        organizationId: AMBADY_ORG_ID,
        name: "River Stone Mix",
        slug: "river-stone-mix",
        description: "Smooth river stones in assorted sizes for pathways and water features.",
        status: "published",
        categorySlug: "landscaping",
        tags: ["stones", "river", "pathway"],
        ratingAvg: 4.3,
        ratingCount: 54,
      },
      {
        id: "prod_gravel_draft",
        organizationId: AMBADY_ORG_ID,
        name: "Decorative Gravel (Draft)",
        slug: "decorative-gravel-draft",
        description: "Fine decorative gravel for planters and zen gardens — not yet published.",
        status: "draft",
        categorySlug: "landscaping",
        tags: ["gravel", "draft"],
        ratingAvg: 0,
        ratingCount: 0,
      },
    ],
    variants: [
      {
        id: v500,
        organizationId: AMBADY_ORG_ID,
        productId,
        name: "500 g",
        sku: "PEB-500G",
        price: 149,
        compareAtPrice: 179,
        stock: 120,
        weightGrams: 500,
        status: "active",
      },
      {
        id: v1kg,
        organizationId: AMBADY_ORG_ID,
        productId,
        name: "1 kg",
        sku: "PEB-1KG",
        price: 279,
        compareAtPrice: 329,
        stock: 85,
        weightGrams: 1000,
        status: "active",
      },
      {
        id: v5kg,
        organizationId: AMBADY_ORG_ID,
        productId,
        name: "5 kg",
        sku: "PEB-5KG",
        price: 1199,
        compareAtPrice: 1399,
        stock: 32,
        weightGrams: 5000,
        status: "active",
      },
      {
        id: "var_river_2kg",
        organizationId: AMBADY_ORG_ID,
        productId: "prod_river_stones",
        name: "2 kg bag",
        sku: "RS-2KG",
        price: 399,
        stock: 45,
        weightGrams: 2000,
        status: "active",
      },
      {
        id: "var_gravel_1kg",
        organizationId: AMBADY_ORG_ID,
        productId: "prod_gravel_draft",
        name: "1 kg bag",
        sku: "GRV-1KG",
        price: 199,
        stock: 0,
        weightGrams: 1000,
        status: "active",
      },
    ],
    media: [
      {
        id: "media_pebbles_1",
        productId,
        url: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800",
        altText: "Ambady Premium Pebbles",
        sortOrder: 0,
        isPrimary: true,
      },
      {
        id: "media_river_1",
        productId: "prod_river_stones",
        url: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800",
        altText: "River Stone Mix",
        sortOrder: 0,
        isPrimary: true,
      },
    ],
    carts: [],
    orders: [],
    customers: [
      {
        id: DEMO_CUSTOMER_ID,
        organizationId: AMBADY_ORG_ID,
        userId: "user_demo_001",
        email: "demo@ambady.local",
        phone: "+919876543210",
        marketingOptIn: true,
      },
    ],
    addresses: [
      {
        id: "addr_demo_001",
        organizationId: AMBADY_ORG_ID,
        customerId: DEMO_CUSTOMER_ID,
        label: "Home",
        name: "Demo Customer",
        phone: "+919876543210",
        line1: "12 Garden Lane",
        city: "Kochi",
        state: "Kerala",
        pincode: "682001",
        isDefault: true,
      },
    ],
    shippingMethods: [
      {
        id: "ship_standard",
        organizationId: AMBADY_ORG_ID,
        code: "standard",
        name: "Standard Delivery",
        baseRate: 49,
        freeAbove: 999,
        isActive: true,
      },
    ],
    promotions: [
      {
        id: "promo_welcome10",
        organizationId: AMBADY_ORG_ID,
        code: "WELCOME10",
        type: "percentage",
        value: 10,
        minCartTotal: 200,
        maxDiscount: 150,
        usageLimit: 1000,
        usageCount: 0,
        isActive: true,
        stackable: false,
      },
    ],
    reviews: [],
    wishlists: [],
    productViews: [],
    tickets: [],
  };
}
